my_pwck:  paswd.o shadw.o grp.o my_pwck.o
	gcc -o my_pwck paswd.o shadw.o grp.o my_pwck.c

paswd.o:paswd.c
	gcc -c paswd.c

shadw.o:shadw.c
	gcc -c shadw.c

grp.o:grp.c
	gcc -c grp.c

my_pwck.o: my_pwck.c
	gcc -c my_pwck.c


